/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author samue
 */
public class ConsultaPessoa extends javax.swing.JPanel {

    /**
     * Creates new form ConsultaPessoaJ
     */
    public ConsultaPessoa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        opPF = new javax.swing.JRadioButton();
        opPJ = new javax.swing.JRadioButton();
        labelCategoriaBusca = new javax.swing.JLabel();
        opPFJ = new javax.swing.JRadioButton();
        separador = new javax.swing.JSeparator();
        posOPLabel = new javax.swing.JLabel();
        labelNome = new javax.swing.JLabel();
        tNome = new javax.swing.JTextField();
        labelCPFeCNPJ = new javax.swing.JLabel();
        tCadastro = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        buscar = new javax.swing.JButton();
        bPrintAll = new javax.swing.JButton();
        bPrintSelecionado = new javax.swing.JButton();

        opPF.setText("Pessoas Físicas");
        opPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opPFActionPerformed(evt);
            }
        });

        opPJ.setText("Pessoas Jurídicas");
        opPJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opPJActionPerformed(evt);
            }
        });

        labelCategoriaBusca.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelCategoriaBusca.setText("Buscar em:");

        opPFJ.setText("Todas (Jurídicas/Físicas)");
        opPFJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opPFJActionPerformed(evt);
            }
        });

        posOPLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        posOPLabel.setText("Nome ou Cadastro");

        labelNome.setText("Nome:");

        labelCPFeCNPJ.setText("CPF:");

        tCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tCadastroActionPerformed(evt);
            }
        });

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nome", "Cadastro", "Data Cadastro", "Valor Total de Compras"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabela);

        buscar.setText("Buscar");

        bPrintAll.setText("PDF (Todos do Resultado)");
        bPrintAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPrintAllActionPerformed(evt);
            }
        });

        bPrintSelecionado.setText("Exibir PDF (Selecionado)");
        bPrintSelecionado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPrintSelecionadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(separador, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(opPFJ)
                            .addComponent(opPF)
                            .addComponent(opPJ)
                            .addComponent(labelCategoriaBusca, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelCPFeCNPJ)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelNome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tNome, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(11, 11, 11)
                                        .addComponent(posOPLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(18, 18, 18)
                        .addComponent(buscar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bPrintSelecionado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bPrintAll, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(posOPLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelCategoriaBusca))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(opPF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(opPJ)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(opPFJ))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(labelNome)
                                    .addComponent(tNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(labelCPFeCNPJ)
                                    .addComponent(tCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(buscar)
                                .addGap(14, 14, 14)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(separador, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bPrintSelecionado)
                    .addComponent(bPrintAll))
                .addContainerGap(18, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void opPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opPFActionPerformed

    private void opPJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opPJActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opPJActionPerformed

    private void opPFJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opPFJActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opPFJActionPerformed

    private void tCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tCadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tCadastroActionPerformed

    private void bPrintAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPrintAllActionPerformed
        bPrintAll.setEnabled(false);
    }//GEN-LAST:event_bPrintAllActionPerformed

    private void bPrintSelecionadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPrintSelecionadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bPrintSelecionadoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bPrintAll;
    private javax.swing.JButton bPrintSelecionado;
    private javax.swing.JButton buscar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelCPFeCNPJ;
    private javax.swing.JLabel labelCategoriaBusca;
    private javax.swing.JLabel labelNome;
    private javax.swing.JRadioButton opPF;
    private javax.swing.JRadioButton opPFJ;
    private javax.swing.JRadioButton opPJ;
    private javax.swing.JLabel posOPLabel;
    private javax.swing.JSeparator separador;
    private javax.swing.JTextField tCadastro;
    private javax.swing.JTextField tNome;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
}
