/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.EsboçoPaineis;

/**
 *
 * @author samue
 */
public class ConsultaEmpenho extends javax.swing.JPanel {

    /**
     * Creates new form ConsultaEmpenho
     */
    public ConsultaEmpenho() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        opEntrada = new javax.swing.JRadioButton();
        opSaida = new javax.swing.JRadioButton();
        labelTipoBusca = new javax.swing.JLabel();
        scroll = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        opAll = new javax.swing.JRadioButton();
        buscar = new javax.swing.JButton();
        separador = new javax.swing.JSeparator();
        labelPeriodo = new javax.swing.JLabel();
        tPeriodoInicial = new javax.swing.JTextField();
        a = new javax.swing.JLabel();
        tPeriodoFinal = new javax.swing.JTextField();
        labelNumeroEmpenho = new javax.swing.JLabel();
        tFornecedor = new javax.swing.JTextField();
        tNumeroEmpenho = new javax.swing.JTextField();
        labelFornecedor = new javax.swing.JLabel();
        bPrintAll = new javax.swing.JButton();
        bPrintSelecionado = new javax.swing.JButton();

        opEntrada.setText("Entradas");
        opEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opEntradaActionPerformed(evt);
            }
        });

        opSaida.setText("Saídas");
        opSaida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opSaidaActionPerformed(evt);
            }
        });

        labelTipoBusca.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelTipoBusca.setText("Tipo de Busca");

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Número", "Entrada/Saída", "Data Cadastro", "Itens", "Valor", "Processo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        scroll.setViewportView(tabela);

        opAll.setText("Todas (Entradas/Saídas)");
        opAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opAllActionPerformed(evt);
            }
        });

        buscar.setText("Buscar");

        labelPeriodo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelPeriodo.setText("Período:");

        tPeriodoInicial.setText("  - - / - - / - -");
        tPeriodoInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tPeriodoInicialActionPerformed(evt);
            }
        });

        a.setText("à");

        tPeriodoFinal.setText("  - - / - - / - -");
        tPeriodoFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tPeriodoFinalActionPerformed(evt);
            }
        });

        labelNumeroEmpenho.setText("Número Empenho: ");

        labelFornecedor.setText("Fornecedor:");

        bPrintAll.setText("PDF (Todos do Resultado)");
        bPrintAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPrintAllActionPerformed(evt);
            }
        });

        bPrintSelecionado.setText("Exibir PDF (Selecionado)");
        bPrintSelecionado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPrintSelecionadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(separador, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(opEntrada)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tPeriodoInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(a)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tPeriodoFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(labelNumeroEmpenho))
                                    .addComponent(opSaida))
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(tNumeroEmpenho, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(buscar))
                                    .addComponent(tFornecedor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(opAll)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                                .addComponent(labelFornecedor))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelTipoBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(193, 193, 193))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(172, 172, 172)
                                .addComponent(labelPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bPrintSelecionado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bPrintAll, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelTipoBusca)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(opEntrada)
                            .addComponent(tPeriodoInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(a)
                            .addComponent(tPeriodoFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelPeriodo))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelFornecedor)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(opSaida)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(opAll)))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buscar)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelNumeroEmpenho)
                        .addComponent(tNumeroEmpenho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separador, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bPrintAll)
                    .addComponent(bPrintSelecionado))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void opEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opEntradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opEntradaActionPerformed

    private void opSaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opSaidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opSaidaActionPerformed

    private void opAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opAllActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opAllActionPerformed

    private void tPeriodoInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tPeriodoInicialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tPeriodoInicialActionPerformed

    private void tPeriodoFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tPeriodoFinalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tPeriodoFinalActionPerformed

    private void bPrintAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPrintAllActionPerformed
        bPrintAll.setEnabled(false);
    }//GEN-LAST:event_bPrintAllActionPerformed

    private void bPrintSelecionadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPrintSelecionadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bPrintSelecionadoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel a;
    private javax.swing.JButton bPrintAll;
    private javax.swing.JButton bPrintSelecionado;
    private javax.swing.JButton buscar;
    private javax.swing.JLabel labelFornecedor;
    private javax.swing.JLabel labelNumeroEmpenho;
    private javax.swing.JLabel labelPeriodo;
    private javax.swing.JLabel labelTipoBusca;
    private javax.swing.JRadioButton opAll;
    private javax.swing.JRadioButton opEntrada;
    private javax.swing.JRadioButton opSaida;
    private javax.swing.JScrollPane scroll;
    private javax.swing.JSeparator separador;
    private javax.swing.JTextField tFornecedor;
    private javax.swing.JTextField tNumeroEmpenho;
    private javax.swing.JTextField tPeriodoFinal;
    private javax.swing.JTextField tPeriodoInicial;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
}
